# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Luminosity' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Luminosity
  
  pod 'Google/SignIn'

  target 'Luminosity-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LuminosityTests' do
    inherit! :search_paths
    # Pods for testing
  end

end